const projects = [
  {
    id: 1,
    title: "Roaming the World’s Pathways1",
    subtitle: "Interior Architecture",
    href: "/work/1",
    src: "/assets/work/architecture/1/5.jpg",
    bannerImages: [
      "/assets/work/architecture/1/3.jpg",
      "/assets/work/architecture/1/4.jpg",
      "/assets/work/architecture/1/8.jpg",
      // "/assets/work/architecture/1/12.jpg",
    ],
    images: [
      "/assets/work/architecture/1/1.jpg",
      "/assets/work/architecture/1/2.jpg",
      "/assets/work/architecture/1/3.jpg",
      "/assets/work/architecture/1/4.jpg",
      "/assets/work/architecture/1/5.jpg",
      "/assets/work/architecture/1/6.jpg",
      "/assets/work/architecture/1/7.jpg",
      "/assets/work/architecture/1/8.jpg",
      "/assets/work/architecture/1/9.jpg",
      "/assets/work/architecture/1/10.jpg",
      "/assets/work/architecture/1/11.jpg",
    ],
  },
  {
    id: 2,
    title: "Roaming the World’s Pathways2",
    subtitle: "Food",
    href: "/work/2",
    src: "/assets/work/food/1.jpg",
    bannerImages: [
      "/assets/work/food/1.jpg",
      "/assets/work/food/2.jpg",
      "/assets/work/food/3.jpg",
      // "/assets/work/architecture/1/12.jpg",
    ],
    images: [
      "/assets/work/food/1.jpg",
      "/assets/work/food/2.jpg",
      "/assets/work/food/3.jpg",
      "/assets/work/food/4.jpg",
      "/assets/work/food/5.jpg",
      "/assets/work/food/6.jpg",
    ],
  },
  {
    id: 3,
    title: "Roaming the World’s Pathways3",
    subtitle: "Interior Architecture",
    href: "/work/3",
    src: "/assets/work/architecture/2/8.jpg",
    bannerImages: [
      "/assets/work/architecture/2/3.jpg",
      "/assets/work/architecture/2/4.jpg",
      "/assets/work/architecture/2/8.jpg",
      // "/assets/work/architecture/1/12.jpg",
    ],
    images: [
      "/assets/work/architecture/2/1.jpg",
      "/assets/work/architecture/2/2.jpg",
      "/assets/work/architecture/2/3.jpg",
      "/assets/work/architecture/2/4.jpg",
      "/assets/work/architecture/2/5.jpg",
      "/assets/work/architecture/2/6.jpg",
      "/assets/work/architecture/2/7.jpg",
      "/assets/work/architecture/2/8.jpg",
      "/assets/work/architecture/2/9.jpg",
      "/assets/work/architecture/2/10.jpg",
      "/assets/work/architecture/2/11.jpg",
      "/assets/work/architecture/2/12.jpg",
      "/assets/work/architecture/2/13.jpg",
      "/assets/work/architecture/2/14.jpg",
      "/assets/work/architecture/2/15.jpg",
      "/assets/work/architecture/2/16.jpg",
      "/assets/work/architecture/2/17.jpg",
      "/assets/work/architecture/2/18.jpg",
      "/assets/work/architecture/2/19.jpg",
      "/assets/work/architecture/2/20.jpg",
      "/assets/work/architecture/2/21.jpg",
    ],
  },
  {
    id: 4,
    title: "Roaming the World’s Pathways4",
    subtitle: "Concert",
    href: "/work/4",
    src: "/assets/work/concert/1/14.jpg",
    bannerImages: [
      "/assets/work/concert/1/1.jpg",
      "/assets/work/concert/1/2.jpg",
      "/assets/work/concert/1/3.jpg",
    ],
    images: [
      "/assets/work/concert/1/1.jpg",
      "/assets/work/concert/1/2.jpg",
      "/assets/work/concert/1/3.jpg",
      "/assets/work/concert/1/4.jpg",
      "/assets/work/concert/1/5.jpg",
    ],
  },
  {
    id: 5,
    title: "Roaming the World’s Pathways5",
    subtitle: "Fashion",
    href: "/work/5",
    src: "/assets/work/fashion/1/5.jpg",
    bannerImages: [
      "/assets/work/fashion/1/2.jpg",
      "/assets/work/fashion/1/3.jpg",
      "/assets/work/fashion/1/4.jpg",
    ],
    images: [
      "/assets/work/fashion/1/1.jpg",
      "/assets/work/fashion/1/2.jpg",
      "/assets/work/fashion/1/3.jpg",
      "/assets/work/fashion/1/4.jpg",
      "/assets/work/fashion/1/5.jpg",
    ],
  },
  {
    id: 6,
    title: "Roaming the World’s Pathways6",
    subtitle: "Interior Architecture",
    href: "/work/6",
    src: "/assets/work/architecture/5/2.jpg",
    bannerImages: [
      "/assets/work/architecture/3/3.jpg",
      "/assets/work/architecture/3/4.jpg",
      "/assets/work/architecture/3/8.jpg",
    ],
    images: [
      "/assets/work/architecture/3/1.jpg",
      "/assets/work/architecture/3/2.jpg",
      "/assets/work/architecture/3/3.jpg",
      "/assets/work/architecture/3/4.jpg",
      "/assets/work/architecture/3/5.jpg",
      "/assets/work/architecture/3/6.jpg",
      "/assets/work/architecture/3/7.jpg",
      "/assets/work/architecture/3/8.jpg",
      "/assets/work/architecture/3/9.jpg",
      "/assets/work/architecture/3/10.jpg",
      "/assets/work/architecture/3/11.jpg",
      "/assets/work/architecture/3/12.jpg",
      "/assets/work/architecture/3/13.jpg",
      "/assets/work/architecture/3/14.jpg",
      "/assets/work/architecture/3/15.jpg",
      "/assets/work/architecture/3/16.jpg",
      "/assets/work/architecture/3/17.jpg",
      "/assets/work/architecture/3/18.jpg",
    ],
  },
];

export default projects;
