const projects = [
  {
    id: 1,
    title: "Green Atrium",
    subtitle: "Sustainable City Design",
    href: "/work/architecture/1",
    src: "/assets/work/architecture/1/1.jpg",
    bannerImages: ["/assets/work/architecture/1/1.jpg"],
    images: [
      "/assets/work/architecture/1/1.jpg",
      "/assets/work/architecture/1/10.jpg",
      "/assets/work/architecture/1/11.jpg",
      "/assets/work/architecture/1/2.jpg",
      "/assets/work/architecture/1/3.jpg",
      "/assets/work/architecture/1/4.jpg",
      "/assets/work/architecture/1/5.jpg",
      "/assets/work/architecture/1/6.jpg",
      "/assets/work/architecture/1/7.jpg",
      "/assets/work/architecture/1/8.jpg",
      "/assets/work/architecture/1/9.jpg",
    ],
    meta: {
      title: "Green Atrium",
      subtitle: "Sustainable City Design",
      client: "Jane & Piece Morgan",
      location: "Melbourne CBD, Vic",
      date: "April 2023",
    },
  },
  {
    id: 2,
    title: "Glass Tower",
    subtitle: "Modern Elegance",
    href: "/work/architecture/2",
    src: "/assets/work/architecture/2/1.jpg",
    bannerImages: ["/assets/work/architecture/2/1.jpg"],
    images: [
      "/assets/work/architecture/2/1.jpg",
      "/assets/work/architecture/2/10.jpg",
      "/assets/work/architecture/2/11.jpg",
      "/assets/work/architecture/2/12.jpg",
      "/assets/work/architecture/2/13.jpg",
      "/assets/work/architecture/2/14.jpg",
      "/assets/work/architecture/2/15.jpg",
      "/assets/work/architecture/2/16.jpg",
      "/assets/work/architecture/2/17.jpg",
      "/assets/work/architecture/2/18.jpg",
      "/assets/work/architecture/2/19.jpg",
      "/assets/work/architecture/2/2.jpg",
      "/assets/work/architecture/2/20.jpg",
      "/assets/work/architecture/2/21.jpg",
      "/assets/work/architecture/2/3.jpg",
      "/assets/work/architecture/2/4.jpg",
      "/assets/work/architecture/2/5.jpg",
      "/assets/work/architecture/2/6.jpg",
      "/assets/work/architecture/2/7.jpg",
      "/assets/work/architecture/2/8.jpg",
      "/assets/work/architecture/2/9.jpg",
    ],
    meta: {
      title: "Glass Tower",
      subtitle: "Modern Elegance",
      client: "Jane & Piece Morgan",
      location: "Melbourne CBD, Vic",
      date: "April 2023",
    },
  },
  {
    id: 3,
    title: "Classic Reimagined",
    subtitle: "Traditional Meets Modern",
    href: "/work/architecture/3",
    src: "/assets/work/architecture/3/5.jpg",
    bannerImages: ["/assets/work/architecture/3/1.jpg"],
    images: [
      "/assets/work/architecture/3/1.jpg",
      "/assets/work/architecture/3/10.jpg",
      "/assets/work/architecture/3/11.jpg",
      "/assets/work/architecture/3/12.jpg",
      "/assets/work/architecture/3/13.jpg",
      "/assets/work/architecture/3/14.jpg",
      "/assets/work/architecture/3/15.jpg",
      "/assets/work/architecture/3/16.jpg",
      "/assets/work/architecture/3/17.jpg",
      "/assets/work/architecture/3/18.jpg",
      "/assets/work/architecture/3/2.jpg",
      "/assets/work/architecture/3/3.jpg",
      "/assets/work/architecture/3/4.jpg",
      "/assets/work/architecture/3/5.jpg",
      "/assets/work/architecture/3/6.jpg",
      "/assets/work/architecture/3/7.jpg",
      "/assets/work/architecture/3/8.jpg",
      "/assets/work/architecture/3/9.jpg",
    ],
    meta: {
      title: "Classic Reimagined",
      subtitle: "Traditional Meets Modern",
      client: "Jane & Piece Morgan",
      location: "Melbourne CBD, Vic",
      date: "April 2023",
    },
  },
  {
    id: 4,
    title: "The Loft",
    subtitle: "Versatile Living Spaces",
    href: "/work/architecture/4",
    src: "/assets/work/architecture/4/1.jpg",
    bannerImages: ["/assets/work/architecture/4/1.jpg"],
    images: [
      "/assets/work/architecture/4/1.jpg",
      "/assets/work/architecture/4/2.jpg",
      "/assets/work/architecture/4/3.jpg",
      "/assets/work/architecture/4/4.jpg",
      "/assets/work/architecture/4/5.jpg",
    ],
    meta: {
      title: "The Loft",
      subtitle: "Versatile Living Spaces",
      client: "Jane & Piece Morgan",
      location: "Melbourne CBD, Vic",
      date: "April 2023",
    },
  },
  {
    id: 5,
    title: "Beach House",
    subtitle: "Elegant Coastal Retreat",
    href: "/work/architecture/5",
    src: "/assets/work/architecture/5/1.jpg",
    bannerImages: ["/assets/work/architecture/5/1.jpg"],
    images: [
      "/assets/work/architecture/5/1.jpg",
      "/assets/work/architecture/5/10.jpg",
      "/assets/work/architecture/5/11.jpg",
      "/assets/work/architecture/5/12.jpg",
      "/assets/work/architecture/5/2.jpg",
      "/assets/work/architecture/5/3.jpg",
      "/assets/work/architecture/5/4.jpg",
      "/assets/work/architecture/5/5.jpg",
      "/assets/work/architecture/5/6.jpg",
      "/assets/work/architecture/5/7.jpg",
      "/assets/work/architecture/5/8.jpg",
      "/assets/work/architecture/5/9.jpg",
    ],
    meta: {
      title: "Beach House",
      subtitle: "Elegant Coastal Retreat",
      client: "Jane & Piece Morgan",
      location: "Melbourne CBD, Vic",
      date: "April 2023",
    },
  },
  {
    id: 6,
    title: "Artisan Bistro",
    subtitle: "Local Flavors, Refined",
    href: "/work/food/1",
    src: "/assets/work/food/1/1.jpg",
    bannerImages: ["/assets/work/food/1/1.jpg"],
    images: [
      "/assets/work/food/1/1.jpg",
      "/assets/work/food/1/2.jpg",
      "/assets/work/food/1/3.jpg",
      "/assets/work/food/1/4.jpg",
      "/assets/work/food/1/5.jpg",
    ],
    meta: {
      title: "Artisan Bistro",
      subtitle: "Local Flavors, Refined",
      client: "Jane & Piece Morgan",
      location: "Melbourne CBD, Vic",
      date: "April 2023",
    },
  },
  {
    id: 7,
    title: "Grand Performance",
    subtitle: "Music Meets Architecture",
    href: "/work/concert/1",
    src: "/assets/work/concert/1/1.jpg",
    bannerImages: ["/assets/work/concert/1/1.jpg"],
    images: [
      "/assets/work/concert/1/1.jpg",
      "/assets/work/concert/1/10.jpg",
      "/assets/work/concert/1/11.jpg",
      "/assets/work/concert/1/12.jpg",
      "/assets/work/concert/1/17.jpg",
      "/assets/work/concert/1/18.jpg",
      "/assets/work/concert/1/2.jpg",
      "/assets/work/concert/1/3.jpg",
      "/assets/work/concert/1/4.jpg",
      "/assets/work/concert/1/5.jpg",
      "/assets/work/concert/1/7.jpg",
      "/assets/work/concert/1/8.jpg",
    ],
    meta: {
      title: "Grand Performance",
      subtitle: "Music Meets Architecture",
      client: "Jane & Piece Morgan",
      location: "Melbourne CBD, Vic",
      date: "April 2023",
    },
  },
  {
    id: 8,
    title: "Couture Collection",
    subtitle: "Classic Meets Modern",
    href: "/work/fashion/1",
    src: "/assets/work/fashion/1/1.jpg",
    bannerImages: ["/assets/work/fashion/1/1.jpg"],
    images: [
      "/assets/work/fashion/1/1.jpg",
      "/assets/work/fashion/1/2.jpg",
      "/assets/work/fashion/1/3.jpg",
      "/assets/work/fashion/1/4.jpg",
      "/assets/work/fashion/1/5.jpg",
    ],
    meta: {
      title: "Couture Collection",
      subtitle: "Classic Meets Modern",
      client: "Jane & Piece Morgan",
      location: "Melbourne CBD, Vic",
      date: "April 2023",
    },
  },
  {
    id: 9,
    title: "Street Style",
    subtitle: "Bold Urban Fashion",
    href: "/work/fashion/2",
    src: "/assets/work/fashion/2/1.jpg",
    bannerImages: ["/assets/work/fashion/2/2.jpg"],
    images: [
      "/assets/work/fashion/2/1.jpg",
      "/assets/work/fashion/2/2.jpg",
      "/assets/work/fashion/2/3.jpg",
      "/assets/work/fashion/2/4.jpg",
      "/assets/work/fashion/2/5.jpg",
      "/assets/work/fashion/2/6.jpg",
    ],
    meta: {
      title: "Street Style",
      subtitle: "Bold Urban Fashion",
      client: "Jane & Piece Morgan",
      location: "Melbourne CBD, Vic",
      date: "April 2023",
    },
  },
];

export default projects;
